package:
  name: vtk          # lower case name of package, may contain '-' but no spaces
  version: "6.2"    # version of package. Should use the PEP-386 verlib

source:
  git_url: https://github.com/Kitware/VTK
  git_tag: v6.2.0

build:
  number: 0
  binary_relocation: true # (defaults to true)

requirements:
  build:
    - python
    - cython
    - numpy
    - cmake
    - tbb

#  # Packages required to run the package. These are the dependencies that
#  # will be installed automatically whenever the package is installed.
  run:
    - python
    - numpy
    - tbb

about:
  home: http://vtk.org
  summary: This library is a Python binding of FCL library.
  license: BSD
